//catagories Data
export const VIEW_CATAGORIES_DATA = "VIEW_CATAGORIES_DATA"
export const UPDATE_CATAGORIES_DATA = "UPDATE_CATAGORIES_DATA"
export const DELETE_CATAGORY_DATA= "DELETE_CATAGORY_DATA"

//view sub catagories
export const GET_ID_VIEW_CATAGORY = "GET_ID_VIEW_CATAGORY" //save id of catagory(based on that view sub catagory)
export const VIEW_SUB_CATAGORY_DATA = "VIEW_SUB_CATAGORY_DATA"
export const UPDATE_SUB_CATAGORIES_DATA = "UPDATE_SUB_CATAGORIES_DATA"
export const DELETE_SUB_CATAGORY_DATA = "DELETE_SUB_CATAGORY_DATA"

//products
export const VIEW_PRODUCT_DATA_FP = "VIEW_PRODUCT_DATA_FP"
export const VIEW_PRODUCT_DATA_ID = "VIEW_PRODUCT_DATA_ID" //SAVE DATA WITH PERTICULAR ID
export const UPDATE_PRODUCT_DATA = "UPDATE_PRODUCT_DATA"
export const DELETE_PRODUCT = "DELETE_PRODUCT"